# Generated by Django 4.2.1 on 2023-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="education",
            field=models.CharField(
                choices=[
                    ("Bachelors", "Bachelors"),
                    ("Masters", "Masters"),
                    ("Phd", "Phd"),
                ],
                default="Bachelors",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Business", "Business"),
                    ("Information Technology", "It"),
                    ("Banking", "Banking"),
                    ("Education/Training", "Education"),
                    ("Telecommunication", "Telecommunication"),
                    ("Others", "Others"),
                ],
                default="Information Technology",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="jobType",
            field=models.CharField(
                choices=[
                    ("FullTime", "Fulltime"),
                    ("PartTime", "Parttime"),
                    ("Intership", "Intership"),
                ],
                default="FullTime",
                max_length=10,
            ),
        ),
    ]
